### ISSUE TITLE
Can't Disable SIP in Big Sur 11.3.1

### ISSUE THREAD

**Issue by CDN18** [leocg/Hackintosh-Dell-G5-5590#10]
Hello, thanks very much for the EFI ! It has been functioning perfectly until I upgraded the system to Big Sur 11.3.1. I'm trying to disable SIP to install a driver but my operation disabling the SIP did not have any effect. I executed `csrutil disable` several times in Recovery Mode but the SIP status remains enabled no matter what I do. 

Have you ever encountered the same problem? Do you think that the problem is related to the OpenCore configuration?

The configuration I used is your latest release(v2.6-OC-0.6.9)

**Comment by leocg** [comment]
Hi, to disable SIP in OpenCore you need to set the property `csr-active-config` to `FF0F0000`

Also check if you have `csr-active-config` at `NVRAM -> Delete -> 7C436110-AB2A-4BBB-A880-FE41995C9F82`

You can find more information about disabling SIP in OpenCore [here](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/post-issues.html#disabling-sip).

Hope it helps, let me know if it works for you to close the issue.

**Comment by CDN18** [comment]
Thanks very much for the guidance, I successfully disabled SIP and installed the extension!
