### ISSUE TITLE
ports HDMI and MINI DISPLAY PORT

### ISSUE THREAD

**Issue by LuanPereiraLima** [leocg/Hackintosh-Dell-G5-5590#12]
Hellow,

I installed Big Sur, but I can't use the HDMI and MINI DISPLAY PORT ports available on the notebook. Is there any way to detect these outputs?

**Comment by LuanPereiraLima** [comment]
Poxa, acabei de descobrir que vc é BR! Hahaha

Outra coisa que está acontecendo comigo é que caso eu remova o pen drive de instalação, eu não enxergo uma forma de dar boot no Big Sur. Eu estou utilizando o Ubuntu em dual boot com ele (um SSD e um NVME separados). Não sei se preciso fazer outro passo para isso ficar fixo. 


Essa foi a única etapa que não executei ->

It's recommended to disable CFG Lock in bios using MobGrubShell. If you disabled it, don't change the lines below. In case you don't want to mess with it, you have to change 2 properties under Kernel->Quirks:

**Comment by leocg** [comment]
Opa, tudo beleza?

Com relação às saídas HDMI e Mini Display Port não é possível utilizar no macOS porque ambas são ligadas diretamente no dGPU. A única saída de vídeo ligada à Intel seria a Thunderbolt/USB-C. Eu utilizo um adaptador USB-C para HDMI em conjunto com o SMBIOS MacBookPro15,2 (o único que consegui funcionar com o monitor externo. Os outros SMBIOS não dão sinal).

Para dar o boot sem precisar do pen drive, você precisa copiar a pasta EFI do pen drive para a partição EFI do seu HD. No meu notebook eu tenho 1 NVME e 1 SSD. No EFI do NVME fica o bootloader do Windows e no EFI do SSD eu coloquei o OpenCore. No seu caso eu acredito que basta copiar a pasta EFI para o SSD/NVME que não contém o bootloader do Linux. Caso não apareça a opção do OpenCore quando reiniciar e pressionar F12, você pode entrar no BIOS e adicionar manualmente o arquivo OpenCore.efi ou o BOOTx64.efi. Recomendo o OpenCore.efi, quando seleciono o BOOTx64.efi o notebook reinicia 1 vez antes de entrar no bootloader.

**Comment by LuanPereiraLima** [comment]
Opa, tudo beleuza!

em relação a inicialização aqui deu tudo certo, fiz o mesmo passo que vc sugeriu, e havia funcionado :).

Sobre as saídas, foi o que eu havia imaginado, em alguns lugares outras pessoas também falam sobre a relação entre a dGPU. Nesse caso, vou atrás de um adaptador pra fazer meu monitor funcionar em conjunto. 

Abraço!

**Comment by nerijunior** [comment]
@LuanPereiraLima eu consegui um usado da Apple aquele thunderbolt -> HDMI + USB + Thunderbold no ML, fica de olho do ML, OLX da tua região, aqui está funcionando quase 100% o único problema é que ele não replica o USB-C no adaptador.
