### ISSUE TITLE
Como atualizar as versões novas?

### ISSUE THREAD

**Issue by nerijunior** [leocg/Hackintosh-Dell-G5-5590#13]
Quando você solta um update, qual seria o fluxo padrão para update?

**Comment by leocg** [comment]
Recomendo o fluxo a seguir:

- Baixe a versão desejada (Ex.: EFI_Dell_G5_v2.10_OpenCore_0.7.3-OpenCanopy_AudioDxe.zip)
- Formate um pen drive como FAT e GUID Partition Table
- Monte a partição EFI do pen drive
- Copie a pasta EFI do arquivo descompactado para a raiz da pasta EFI do pen drive
- Dê um boot utilizando o OpenCore via pen drive e verifique se o sistema inicializa corretamente
- Caso inicialize corretamente, copie a pasta EFI para a partição EFI do OpenCore, substituindo a versão anterior.

Você pode pular a etapa do pen drive, mas normalmente faço dessa forma para ter uma versão funcional do EFI caso tenha algum problema com a nova versão.

Lembrando que se não tiver desabilitado o CFG Lock no BIOS, deverá mudar 2 parâmetros no config.plist, em Kernel->Quirks:
AppleCpuPmCfgLock -> mudar para YES or 1
AppleXcpmCfgLock -> mudar para YES or 1

Se tiver desabilitado o CFG Lock no BIOS, não precisa alterar nenhum parâmetro.

Se o processo acima der certo, me sinaliza para fechar o chamado!

**Comment by nerijunior** [comment]
Tudo certo, funcionou certinho e o Bigsur atualizou normalmente.

**Comment by leocg** [comment]
Beleza! Lembre apenas se sempre utilizar os mesmos seriais do config.plist quando atualizar o OpenCore, para garantir o funcionamento normal do OS. 

Quando o serial é alterado e o computador é reiniciado você precisará logar novamente nas contas do iCloud, Apple Music, etc e um daemon de verificação de integridade do sistema ficará rodando em segundo plano consumindo bastante CPU durante algum tempo.
