### ISSUE TITLE
Utilizacao HDMI 

### ISSUE THREAD

**Issue by pedromadethis** [leocg/Hackintosh-Dell-G5-5590#14]
Queria utilizar um monitor externo via hdmi, mas ele ta funcionando, sabe se isso rola por causa da rtx? tem algum jeito de configurar pra igpu?

Tentei display port para hdmi (acredito que nao funcione devido a rtx) , e hdmi somente, meu medo acaba sendo de investir em um hub usb > hdmi e nao funcionar tambem.

**Comment by leocg** [comment]
Esse laptop possui as saídas HDMI e Display Port ligados diretamente da RTX. A única porta ligada ao iGPU é a USB-C, então é necessário utilizar um adaptador USB-C para HDMI, estou usando essa configuração para usar o monitor externo sem problemas há aproximadamente 1 ano.

Estava usando um genérico que funcionava tranquilo, mas a qualidade era ruim e ele parou de funcionar. Comprei na semana passada esse aqui: https://www.amazon.com.br/gp/product/B088GDM4FC/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1

Está funcionando normalmente via HDMI. Tenho um cabo HDMI-VGA e funciona também, quando coloco o HDMI no adaptador e o VGA no monitor.

Acho que vc acabou de mandar uma mensagem no privado do MacMagazine, colei a mesma resposta aqui
