### ISSUE TITLE
Trackpad doesn't work on Bigsur 11.16

### ISSUE THREAD

**Issue by Kergli** [leocg/Hackintosh-Dell-G5-5590#19]
Just don't know why

**Comment by nitrox710** [comment]
u can fix that with some kext, i cant boot into monterey but was a easy fix, just search a little bit :)

**Comment by leocg** [comment]
Wait a few seconds in opencore boot picker before pressing enter. Sometimes the trackpad won't work if I press enter just after opencore appears.
