### ISSUE TITLE
Can't boot - GTX 1660ti version

### ISSUE THREAD

**Issue by radaelilucca** [leocg/Hackintosh-Dell-G5-5590#2]
Hi man!

I saw your post in somewhere and decide to try catalina again. I'm trying to install but it cant even boot. Ive tried your folder and one made from scratch following the opencore guide, but both get in the same error. After this part the screen goes black and remains so until force shutdown.

<img src="https://i.imgur.com/x7EBPhd.jpg" height="300px"/>

Do you have any idea whats happening?

Thanks thanks! 🗡️

**Comment by leocg** [comment]
Hi! Did you put the -wegnoegpu boot-arg to disable dGPU and the alcid=15 to fix audio?

If you have same model as me, you could try the EFI folder located in UTIL/OPENCORE USB BOOT/. The main EFI won't boot if you don't disable BIOS CFG Lock, disable dGPU using ACPI and other tweaks.

**Comment by radaelilucca** [comment]
> Hi! Did you put the -wegnoegpu boot-arg to disable dGPU and the alcid=15 to fix audio?
> 
> If you have same model as me, you could try the EFI folder located in UTIL/OPENCORE USB BOOT/. The main EFI won't boot if you don't disable BIOS CFG Lock, disable dGPU using ACPI and other tweaks.

Véi, cê é do br... kkkk

Seguinte, to com uma EFI com a ETHERNET funcionando... 100%. Total estável e funcionando na velocidade padrão.
Eu manjo muito pouco de hackintosh ainda, então queria a tua ajuda pra extrair dessa EFI o que quer que seja que faz a ethernet funcionar e por em outra EFI que eu achei mais estável... Ou na tua EFI também, mas pra essa vou precisar de ajuda no proceder do cfg lá. Ta aí uma boa troca, tu me ajuda com a bios que eu te dou a ethernet. kkkks

Essa que funciona ta numa EFI padrão de instalação da imagem.

Me chama em algum lugar pra gente trocar uma ideia! 

[Facebook](https://www.facebook.com/luccaradaeli)
Discord: Lucca Radaeli#4554
[Twitter](https://twitter.com/luccaradaeli)

**Comment by leocg** [comment]
Beleza, chamando pelo Discord!
