### ISSUE TITLE
suddenly system restart !!

### ISSUE THREAD

**Issue by al-jabirr** [leocg/Hackintosh-Dell-G5-5590#26]
I think name driver related fault, here is error log please check it. thanks
![ErrScreenshot 2022-12-01 at 10 47 39 AM](https://user-images.githubusercontent.com/8538407/204970377-5197685b-3c27-4fe3-94f0-36c335c73358.png)

**Comment by leocg** [comment]
Seems to be something related to your NVMe.

Open [Hackintool](https://github.com/benbaker76/Hackintool), click on Disks e verify your disk name. Mine is "BC511 NVMe SK hynix 512GM Media".

The log shows that your drive may be a Samsung one, so maybe you can fix the kernel panic using [NVMeFix kext](https://github.com/acidanthera/NVMeFix).

**Comment by al-jabirr** [comment]
thanks for reply sir. I found some info (--Samsung PM981 and PM991(commonly found in OEM systems like laptops)
Even if PM981 has been fixed with [NVMeFix (opens new window)](https://github.com/acidanthera/NVMeFix/releases) version 1.0.2 there is still plenty of kernel panics issues--)

https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html
