### ISSUE TITLE
I've been getting new kernel panic for a while now

### ISSUE THREAD

**Issue by al-jabirr** [leocg/Hackintosh-Dell-G5-5590#27]
![Screenshot 2022-12-25 at 10 06 19 AM](https://user-images.githubusercontent.com/8538407/209456711-90ef18d4-1a37-48cb-94fa-e152cd7d4999.png)The laptop restarts suddenly after the Apple logo appears **when powering on**, but it does not happen every time it is powered on or **occasionally.**

**Comment by leocg** [comment]
It seems to be related to your NVMe Drive, the kernel panic occurs because of APFS driver. If you have a secondary HDD/SSD on your laptop I suggest trying to install on a new partition in order to test if the issue persists.

**Comment by al-jabirr** [comment]
> It seems to be related to your NVMe Drive, the kernel panic occurs because of APFS driver. If you have a secondary HDD/SSD on your laptop I suggest trying to install on a new partition in order to test if the issue persists.

Yes sir thanks, I will definitely make a new post with this issue 🙂😃 if it solved.
