### ISSUE TITLE
Is it possible to fix built-in wifi ac 9560!!

### ISSUE THREAD

**Issue by al-jabirr** [leocg/Hackintosh-Dell-G5-5590#32]
Sir, it's possible right now?

**Comment by leocg** [comment]
I think it's possible with itlwm

You can try using the EFI attached with necessary kext. Can't test because mine came with a broadcom wifi.
[EFI OpenCanopy INTEL AC 9560.zip](https://github.com/leocg/Hackintosh-Dell-G5-5590/files/10793150/EFI.OpenCanopy.INTEL.AC.9560.zip)

**Comment by al-jabirr** [comment]
I've tested **_all stable versions of itlwn_** since this morning and the kernel ends up panicking and restarting. Whenever I try to connect to a network. Finally, I **alpha release v2.2.0** tested it and it **_works Fine_**.
![Screenshot 2023-02-21 at 5 49 54 PM](https://user-images.githubusercontent.com/8538407/220339764-9083c8d8-d42f-48a0-8df7-67fe6179ca5c.png)
![Screenshot 2023-02-21 at 5 50 22 PM](https://user-images.githubusercontent.com/8538407/220339778-e252ed9d-2ee3-4b58-b008-bb76ae314aa5.png)
