### ISSUE TITLE
|~Menu bar WiFi icon|

### ISSUE THREAD

**Issue by al-jabirr** [leocg/Hackintosh-Dell-G5-5590#33]
Can you help me again, menu bar wifi icon is not showing any network but, when I go to do it from settings it is showing there.

![Screenshot 2023-02-22 at 12.55.26 AM.png](https://user-images.githubusercontent.com/8538407/220437367-1bc1912e-c44d-40e9-b259-3dc78fc6f1a0.png)
![Screenshot 2023-02-22 at 12.55.16 AM.png](https://user-images.githubusercontent.com/8538407/220437387-996abd92-6ee8-4c52-a242-239cae94b5fc.png)

**Comment by leocg** [comment]
You could try [HeliPort](https://openintelwireless.github.io/HeliPort/) app instead of using native macOS menu bar icon. See if it works for you

**Comment by al-jabirr** [comment]
is not working. by the way thnq, it's not a major issue.
