### ISSUE TITLE
Issue after upgrading to Kingston 1tb nvme

### ISSUE THREAD

**Issue by nerijunior** [leocg/Hackintosh-Dell-G5-5590#34]
I upgraded the M2 nvme to an Kingston 1tb 2500mbps (dell website says that 1 tb is the max supported), flashed an usb drive, started using your EFI (thanks again for all effort on it), formatted the SSD, apfs, installed the Mac os and after the reboot, selected MacOs Installer from OpenCore boot selection and after the apple logo loading screen there's an error:

macOs Update Assistant:
com.apple.DiskManagement.disenter error -119930878

IDK the exact reason yet but my guess is that this Kingston nvme has some incompatibility with our hardware. 

If someone can give an idea how can I solve it, please share here to help others.

**Comment by nerijunior** [comment]
That was crazy: one randomly worked after some restarts ( all failing at the same point ). I'm answering this from the new MacOs installation, the nvme is working fine.

![image](https://user-images.githubusercontent.com/17169/236665581-6c48b64d-38ee-4f9e-88eb-195d8719e73e.png)

**Comment by leocg** [comment]
Glad you find a solution! Some NVMe models don't play nice with hackintosh. Please report if you have any issues in the future.
