### ISSUE TITLE
Bluetooth issue after dualbooting.

### ISSUE THREAD

**Issue by nerijunior** [leocg/Hackintosh-Dell-G5-5590#35]
I changed my SSD recently and after installing the macOS using the whole disk everything was fine, wifi and Bluetooth were also working today after installing Windows, drivers, etc. The wifi still working but the Bluetooth is not. 

IDK if it could be related to the Windows Fenvi driver installation because after installing Windows 11 wifi, Bluetooth was not working, and I was forced to install Fenvi driver from the Fenvi website.

How can I investigate to understand if something went wrong? 

System Information:
![image](https://github.com/leocg/Hackintosh-Dell-G5-5590/assets/17169/e7446c1a-6978-41a9-90d3-e457a1dca00a)

Hackintool
![image](https://github.com/leocg/Hackintosh-Dell-G5-5590/assets/17169/c5655735-2dea-4d90-b9e9-4e6d04c4944e)

I already tried to reset NVRAM

**Comment by nerijunior** [comment]
Damn! I was sure that I was using the "BCM94360NG" but I'm using "BCM94352Z".

**Comment by leocg** [comment]
Did you manage to get it working on Windows? You can find all laptop drivers at https://www.fenvi.com/drive.html?id=2

**Comment by nerijunior** [comment]
@leocg yep! The issue was I was installing the wrong driver BCM94360NG instead of BCM94352Z. After changing to the right now everything worked. A question that I'm trying to understand is: how windows installed drivers affect other OS if they don't share the "firmware"

**Comment by leocg** [comment]
I don't think they share information. Sometimes I boot and wifi won't work. But it work again after a reboot. Maybe this was the issue and coincidentally it worked after you installed correct windows drivers and reboot machine.

**Comment by nerijunior** [comment]
I never faced this situation before, I never booted in and the wifi or Bluetooth was not working. I will try it again: go to windows, install the wrong driver again, and login into mac if the issue appears again I still with my question.
