### ISSUE TITLE
Dell G5 5590 OpenCore 0.9.2 , many files ending with 2 in the compressed file?

### ISSUE THREAD

**Issue by cairy** [leocg/Hackintosh-Dell-G5-5590#36]
![截屏2023-06-02 09 04 15](https://github.com/leocg/Hackintosh-Dell-G5-5590/assets/11585905/db2c8319-8392-45bf-a910-cd7461cc2486)

Is this normal? It wasn't like this before.

**Comment by leocg** [comment]
No, Finder kept older files on folder (those ending on 2). You can delete them or wait next release (0.9.3) coming in couple weeks. Keeping them won't harm, because they aren't called in config.plist

**Comment by leocg** [comment]
Fixed duplicated files in new release (OpenCore 0.9.3)
