### ISSUE TITLE
Help to fix brightness

### ISSUE THREAD

**Issue by Ocin4ever** [leocg/Hackintosh-Dell-G5-5590#40]
Good morning,
First of all thank you for your efi file.
I need your help to fix a long standing problem I have with my hackintosh. I have a dell G5 5500 and I managed to get it working and I have the setup with a 300hz screen and it is problematic in macos.
To solve my problem I will need 2 things:

First a screenshot of ioreg in the applebacklightdisplay section. To do this, you need to download apple's ioreg utility then enter the "iGPU" search section and then delete the entry in order to see all the sections. Scroll down a little bit to see "AppleBacklightDisplay" under "display0" under "intelframebuffer@0".
![Capture d’écran 2023-06-29 à 20 49 55](https://github.com/leocg/Hackintosh-Dell-G5-5590/assets/85343782/de35bda5-7bb0-4d91-a5b3-662412c7ecca)

This will allow me to copy your settings which allow for native brightness control.

A second request, if you have time, would be to send me a generated kext using hackintool. To do this, go to the display section and disconnect your external screens. Check the boxes like the screenshot below but don't change the edid section. Finally, click on the export button and multiple files will appear on your desktop. Please send me the kext that has been created.
![Capture d’écran 2023-06-30 à 14 37 15](https://github.com/leocg/Hackintosh-Dell-G5-5590/assets/85343782/ca4c587c-4270-40b7-9613-e6a810a72932)

The kext will allow me to extract the edid from the 144hz screen to spoof mine.

Thanks in advance, I will really appreciate your help

**Comment by leocg** [comment]
Hi, I'm sending below your requests. Hope it helps! I'll leave the topic open in case you need more information.

![Screenshot 2023-07-04 at 10 25 51](https://github.com/leocg/Hackintosh-Dell-G5-5590/assets/3638669/282ecb2d-a376-4cf3-9e2b-1a39b798302c)

<00 ff ff ff ff ff ff 00 09 e5 4a 08 00 00 00 00 01 1c 01 04 a5 22 13 78 02 de 50 a3 54 4c 99 26 0f 50 54 00 00 00 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 9d 85 80 a0 70 38 3e 40 6c 30 aa 00 58 c2 10 00 00 1a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 1a 00 00 00 fe 00 46 35 54 20 50 80 4e 56 31 35 36 46 48 00 00 00 00 00 02 41 2f 9e 02 10 00 00 0b 01 0a 20 20 00 4e>

![Screenshot 2023-07-04 at 10 29 00](https://github.com/leocg/Hackintosh-Dell-G5-5590/assets/3638669/4f50d96d-71ba-477f-894b-0aa9d1f14b47)

[Hackintool Export Display.zip](https://github.com/leocg/Hackintosh-Dell-G5-5590/files/11949788/Hackintool.Export.Display.zip)

**Comment by Ocin4ever** [comment]
Thank you very much for your answer. I noticed there was informations in ioreg that are not present in my ioreg. If it don't bother you, I'll have one last request. Could you send your hole ioreg file (by clicking into file and save as) because there are dictionaries with values inside AppleBacklightDisplay and to avoid wasting your time it would be easier.
thank you so much

**Comment by Ocin4ever** [comment]
PS : If someone ask you again for a dell g5 5500, you can tell him to try to inject the edid of their display. Without that, my computer don't want to show any screen in Mac OS at all.

**Comment by leocg** [comment]
Hi, sorry for the delay, I'm on vacation and without the Dell. I use a MacBook 12" for travels. I'll send your request as soon as I can.

**Comment by leocg** [comment]
Full IOReg below:
[DELL G5 5590.ioreg.zip](https://github.com/leocg/Hackintosh-Dell-G5-5590/files/12074038/DELL.G5.5590.ioreg.zip)

**Comment by Ocin4ever** [comment]
Thank you so much I'm sure it will help me. And sorry I didn't receive the notification of your message.
