### ISSUE TITLE
External HDD not being recognized

### ISSUE THREAD

**Issue by leluque** [leocg/Hackintosh-Dell-G5-5590#5]
Have you been able to use external HDD with your Hackintosh? It appears disabled in Disk Utility and is not recognized.

**Comment by leocg** [comment]
Yes, I can use external HDD normally. Maybe your USB ports aren't mapped correctly. Check USB section in Hackintool to check ports, maybe you'll have to remap them accordly.

**Comment by al-jabirr** [comment]
> Yes, I can use external HDD normally. Maybe your USB ports aren't mapped correctly. Check USB section in Hackintool to check ports, maybe you'll have to remap them accordly.

Yes Sir, my use won't working. Can you tell the procedure how can I remap my usb.
