### ISSUE TITLE
Upgrade opencore and all kexts

### ISSUE THREAD

**Issue by giorgifernandes** [leocg/Hackintosh-Dell-G5-5590#8]
Do you have an update for the opencore and kexts?  I did update my machine but when updating WhateverGreen the brightness stops working, you know what it can be?

**Comment by leocg** [comment]
It's on my todo list, I got some time sensitive jobs this year and couldn't afford to spend time without my machine in case something happens during the update. I think I'll update by the end of the month. Newer versions of OpenCore changed the boot process and need some tweaks. You can try updating other kexts alongside whatevergreen. At least Lilu (whatevergreen is a Lilu plugin) and VirtualSMC. Let me know if it works! 

When Acidanthera release OpenCore 0.6.9 (probably first monday of may) I'm going to catch up with the releases and update this repo.

**Comment by giorgimoreira** [comment]
Great news, I will follow this update.

**Comment by leocg** [comment]
Repo updated with latest OpenCore and kexts, enjoy!
