### ISSUE TITLE
Hey Man

### ISSUE THREAD

**Issue by StrayDawg** [leocg/Hackintosh-Dell-G5-5590#9]
I have a 5590 without a discreet GPU. 
https://www.dell.com/support/home/en-us/product-support/servicetag/0-VTlqc2VsNHJaWmhLREJ1VXo1cFVqQT090/overview
This should work for me as well right?

**Comment by leocg** [comment]
Sup man!

This guide is for Dell G5 5590, your laptop is Dell Latitude 5590, not the same hardware. I found a topic with some EFI files attached at https://osxlatitude.com/forums/topic/15511-latitude-5590-problems-with-bigsur/

I suggest you check there for a compatible EFI file.

**Comment by glnicolas** [comment]
Hey @leocg what about Dell G5 5590 with gtx 1650 model without thunderbolt, can I use this repo?

**Comment by leocg** [comment]
> Hey @leocg what about Dell G5 5590 with gtx 1650 model without thunderbolt, can I use this repo?

You may try the EFI, just skip the CFG Lock session because I don't know if the variable is the same from thunderbolt version.

Change 2 things in config.plist:
AppleCpuPmCfgLock to YES or 1 
AppleXcpmCfgLock to YES or 1
